package org.zerocouplage.api.config;

/**
 * <p>The configuration information of a security element from the Zerocouplage configuration file.
 * 
 *
 */
public interface ISecurityConfig {

	/**
	 * <p>Returns the name of this ISecurityConfig .</p>
	 * 
	 * @return the name of the Orbac Security
	 */
	public String getName();
	/**
	 * <p> Set the Name of this ISecurityConfig </p>
	 * @param name of the Orbac Security
	 */
	public void setName(String name);
	
	/**
	 * Returns the absolute path of the class operating the Orbac Subject Ex:"com.zcrolemanager.impl.controller.ZCRule"
	 * @return absolute path of Orbac's subject class  
	 */
	public String getObject();
	
	/**
	 * Set the absolute path of the class operating the Orbac subject Ex: "com.zcrolemanager.impl.controller.ZCRule"
	 * @param class path of the subject operating class  
	 */
	public void setObject(String object);
	
	/**
	 * Returns the path to locate the Orbac Security policy generated by MotOrbac
	 * @return Orbac Security policy path
	 */
	public String getValueTarget();
	
	/**
	 * Set the path of Orbac Security Policy
	 * @param Orbac Security policy path
	 */
	public void setValueTarget(String valueTarget);

	// role-manager redirection en cas d'erreur vers page d'erreur
	/**
	 * Returns path to the Error page in which the User are forwarded in case of a denied access
	 * @return Error page path
	 */
	public String getErrorPage();
	/**
	 * Set the name of the error page in case of a denied access 
	 * @param errorPage
	 */
	public void setErrorPage(String errorPage);

}
